CHORDS = {
    "I": [["1", "3", "5", "7", "9", "11", "13"], "Major"],
    "ii": [["1", "b3", "5", "b7", "9", "11", "13"], "Minor"],
    "iii": [["1", "b3", "5", "b7", "b9", "11", "b13"], "Minor"],
    "IV": [["1", "3", "5", "7", "9", "#11", "13"], "Major"],
    "V": [["1", "3", "5", "b7", "9", "11", "13"], "Major"],
    "vi": [["1", "b3", "5", "b7", "9", "11", "b13"], "Minor"],
    "vii": [["1", "b3", "b5", "b7", "b9", "11", "b13"], "Half-dminished"],
    "Augmented": [["1", "3", "b6"], "Augmented"],
    "Augmented 11": [["1", "3", "5", "b7", "9", "#11"], "Major"],
    "Augmented M7": [["1", "3", "b6", "7"], "Augmented"],
    "Augmented 7": [["1", "3", "b6", "b7"], "Augmented"],
    "Augmented 6th (Italian)": [["1", "3", "b7"], "Predominant"],
    "Augmented 6th (French)": [["1", "3", "b5", "b7"], "Predominant"],
    "Augmented 6th German)": [["1", "3", "5", "b7"], "Predominant"],
    "dim": [["1", "b3", "b5"], "Diminished"],
    "dim M7": [["1", "b3", "#4", "7"], "Diminished"],
    "dim 7": [["1", "b3", "b5", "6"], "Diminished"],
    "dom": [["1", "3", "5"], "Major"],
    "dom 11": [["1", "3", "5", "b7", "9", "11"], "Major"],
    "dom b9": [["1", "3", "5", "b7", "b9"], "Major"],
    "dom 9": [["1", "3", "5", "b7", "9"], "Major"],
    "dom parallel": [["1", "b3", "5"], "Minor"],
    "7th": [["1", "3", "5", "b7"], "Major"],
    "7th b5": [["1", "3", "#4", "b7"], "Diminished"],
    "7th #9 / Hendrix": [["1", "3", "5", "b7", "#9"], "Major"],
    "dom 13": [["1", "3", "5", "b7", "9", "11", "13"], "Major"],
    "Dream": [["1", "4", "#4", "5"], "Just"],
    "Elektra": [["1", "5", "6", "b9", "3"], "Bitonal"],
    "Farben": [["1", "b6", "7", "3", "13"], "Atonal"],
    "Half-dim 7": [["1", "b3", "#4", "b7"], "Diminished"],
    "Harmonic 7": [["1", "3", "5", "b7"], "Major"],
    "Leading-tone triad": [["1", "b3", "b5"], "Diminished"],
    "Lydian": [["1", "3", "5", "7", "#11"], "Major"],
    "Magic": [["1", "b2", "4", "b5", "b7", "1", "#9", "11"], "Just"],
    "Maj": [["1", "3", "5"], "Major"],
    "Maj eleventh": [["1", "3", "5", "7", "9", "11"], "Major"],
    "Maj 7": [["1", "3", "5", "7"], "Major"],
    "Maj 7 #11": [["1", "3", "b6", "7", "#11"], "Augmented"],
    "Maj 6th": [["1", "3", "5", "6"], "Major"],
    "Maj 6 add 9": [["1", "3", "5", "6", "9"], "Major"],
    "Maj 9th": [["1", "3", "5", "7", "9"], "Major"],
    "Maj 13th": [["1", "3", "5", "7", "9", "#11", "13"], "Major"],
    "Mediant": [["1", "b3", "5"], "Minor"],
    "min": [["1", "b3", "5"], "Minor"],
    "min 11": [["1", "b3", "5", "b7", "9", "11"], "Minor"],
    "min M7": [["1", "b3", "5", "7"], "Minor"],
    "min 9th": [["1", "b3", "5", "b7", "9"], "Minor"],
    "min7": [["1", "b3", "5", "b7"], "Minor"],
    "min 6th": [["1", "b3", "5", "6"], "Minor"],
    "min 6/9": [["1", "b3", "5", "6", "9"], "Minor"],
    "min thirteenth": [["1", "b3", "5", "b7", "9", "11", "13"], "Minor"],
    "Mystic": [["1", "b5", "b7", "3", "13", "9"], "Atonal"],
    "Neapolitan": [["b2", "4", "b6"], "Major"],
    "9 #5": [["1", "3", "b6", "b7", "9"], "Augmented"],
    "9 b5": [["1", "3", "b5", "b7", "9"], "M3+d5"],
    "Northern lights": [
        ["b2", "2", "b6", "1", "#9", "#11", "5", "b7", "7", "3", "5"],
        "Atonal",
    ],
    "Ode-to-Napoleon hexachord": [["1", "b2", "3", "4", "b6", "6"], "Atonal"],
    "Petrushka": [["1", "b2", "3", "b5", "5", "b7"], "Bitonal"],
    "Power chord": [["1", "5"], "Indeterminate"],
    "Psalms": [["1", "b3", "5"], "Minor"],
    "Secondary dominant": [["1", "3", "5"], "Major"],
    "Secondary leading-tone": [["1", "b3", "b5"], "Diminished"],
    "Secondary supertonic": [["1", "b3", "5"], "Minor"],
    "Seven six": [["1", "3", "5", "6", "b7"], "Major"],
    "Seventh suspension four": [["1", "4", "5", "b7"], "Suspended"],
    "So What": [["1", "4", "b7", "#9", "5"], "Bitonal"],
    "Suspended": [["1", "4", "5"], "Suspended"],
    "Subdominant": [["1", "3", "5"], "Major"],
    "Subdominant parallel": [["1", "b3", "5"], "Minor"],
    "Submediant": [["1", "b3", "5"], "Minor"],
    "Subtonic": [["1", "3", "5"], "Major"],
    "Supertonic": [["1", "b3", "5"], "Minor"],
    "13th b9": [["1", "3", "5", "b7", "b9", "13"], "Major"],
    "13th b9 b5": [["1", "3", "b5", "b7", "b9", "13"], "M3+d5"],
    "Tonic counter parallel": [["1", "b3", "5"], "Minor"],
    "Tonic": [["1", "3", "5"], "Major"],
    "Tonic parallel": [["1", "b3", "5"], "Minor"],
    "Tristan": [["1", "b3", "b5", "b7"], "Predominant"],
    "Viennese trichord A": [["1", "b2", "b5"], "Atonal"],
    "Viennese trichord B": [["1", "#4", "5"], "Atonal"],
}
