SCALES = {
    'Acoustic scale':              ['1',  '2',  '3',  '#4', '5',  '6',  'b7'],
    'Aeolian mode':                ['1',  '2',  'b3', '4',  '5',  'b6', 'b7'],
    'Algerian scale':              ['1',  '2',  'b3', '#4', '5',  '6',  '7'],
    'Altered scale':               ['1',  'b2', 'b3', '3',  '#4', 'b6', 'b7'],
    'Augmented scale':             ['1',  'b3', '3',  '5',  'b6', '7'],
    'Bebop dominant scale':        ['1',  '2',  '3',  '4',  '5',  '6',  'b7', '7'],
    'Blues scale':                 ['1',  'b3', '4',  'b5', '5',  'b7'],
    'Dorian mode':                 ['1',  '2',  'b3', '4',  '5',  '6',  'b7'],
    'Double harmonic scale':       ['1',  'b2', '3',  '4',  '5',  'b6', 'b7'],
    'Enigmatic scale':             ['1',  'b2', '3',  '#4', 'b6', 'b7', '7'],
    'Flamenco mode':               ['1',  'b2', '3',  '4',  '5',  'b6', '7'],
    'Gypsy scale':                 ['1',  '2',  'b3', '#4', '5',  'b6', 'b7'],
    'Half diminished scale':       ['1',  '2',  'b3', '4',  'b5', 'b6', 'b7'],
    'Harmonic major scale':        ['1',  '2',  '3',  '4',  '5',  'b6', '7'],
    'Harmonic minor scale':        ['1',  '2',  'b3', '4',  '5',  'b6', '7'],
    'Hirajoshi scale':             ['1',  '3',  '#4', '5',  '7'],
    'Hungarian minor scale':       ['1',  '2',  'b3', '#4', '5',  'b6', '7'],
    'Hungarian major scale':       ['1',  'b3', '3',  '#4', '5',  '6',  'b7'],
    'In scale':                    ['1',  'b2', '4',  '5',  'b6'],
    'Insen scale':                 ['1',  'b2', '4',  '5',  'b7'],
    'Ionian mode':                 ['1',  '2',  '3',  '4',  '5',  '6',  '7'],
    'Istrian scale':               ['1',  'b2', 'b3', '3',  '#4', '5'],
    'Iwato scale':                 ['1',  'b2', '4',  'b5', 'b7'],
    'Locrian mode':                ['1',  'b2', 'b3', '4',  'b5', 'b6', 'b7'],
    'Lydian augmented scale':      ['1',  '2',  '3',  '#4', 'b6', '6',  '7'],
    'Lydian mode':                 ['1',  '2',  '3',  '#4', '5',  '6',  '7'],
    'Major bebop scale':           ['1',  '2',  '3',  '4',  '5',  'b6', '6',  '7'],
    'Major Locrian scale':         ['1',  '2',  '3',  '4',  'b5', 'b6', 'b7'],
    'Major pentatonic scale':      ['1',  '2',  '3',  '5',  '6'],
    'Melodic minor scale':         ['1',  '2',  'b3', '4',  '5',  '6',  '7'],
    'Melodic minor scale ':        ['1',  '2',  'b3', '4',  '5',  '6',  '7'],
    'Minor pentatonic scale':      ['1',  'b3', '4',  '5',  'b7'],
    'Mixolydian mode':             ['1',  '2',  '3',  '4',  '5',  '6',  'b7'],
    'Neapolitan major scale':      ['1',  'b2', 'b3', '4',  '5',  '6',  '7'],
    'Neapolitan minor scale':      ['1',  'b2', 'b3', '4',  '5',  'b6', '7'],
    'Persian scale':               ['1',  'b2', '3',  '4',  'b5', 'b6', '7'],
    'Phrygian dominant scale':     ['1',  'b2', '3',  '4',  '5',  'b6', 'b7'],
    'Phrygian mode':               ['1',  'b2', 'b3', '4',  '5',  'b6', 'b7'],
    'Prometheus scale':            ['1',  '2',  '3',  '#4', '6',  'b7'],
    'Scale of harmonics':          ['1',  'b3', '3',  '4',  '5',  '6'],
    'Tritone scale':               ['1',  'b2', '3',  '#4', '5',  'b7'],
    'Two-semitone tritone scale':  ['1',  'b2', '2',  'b5', '5',  'b6'],
    'Ukrainian Dorian scale':      ['1',  '2',  'b3', '#4', '5',  '6',  'b7'],
    'Whole tone scale':            ['1',  '2',  '3',  '#4', 'b6', 'b7'],
    'Yo scale':                    ['1',  'b3', '4',  '5',  'b7']
    }
